# Generated by Django 3.2.8 on 2024-06-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20240622_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='role',
            field=models.CharField(default='user', max_length=250),
        ),
    ]
